name: Triton Kernel Benchmarking
on:
  pull_request:
  workflow_dispatch:
  schedule:
  # Runs at 12:00 PM UTC, which is 5:00 AM PST
   - cron: '0 12 * * *'

jobs:
  kernel-bench:
    runs-on: amdgpu-mi250-x86-64
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Triton Python Venv
        run: |
          python3.11 -m venv triton_bench
          source triton_bench/bin/activate
          pip install --upgrade pip
          pip install --pre pytorch-triton-rocm torch --index-url https://download.pytorch.org/whl/nightly/rocm6.2
          pip install -r requirements.txt

      - name: Run Kernel Benchmarking
        run: |
          source triton_bench/bin/activate
          pip freeze
          pytest -s kernels
      
      - uses: actions/upload-artifact@master
        with:
          name: perf-artifacts
          path: ./artifacts
